version: '3.8'

services:
  postgresql:
    image: postgres:16.1
    container_name: tg-bot-health-db
    restart: unless-stopped
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - my-network
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg-data:
  pgadmin-data:

networks:
  my-network:
    driver: bridge
